using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using PushBoxz.Core;
using PushBoxz.Data;
using PushBoxz.Presentation;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace PushBoxz.Editor
{
    public class PushBoxzLevelEditorWindow : EditorWindow
    {
        private const string LevelsFolder = "Assets/PushBoxz/Levels";
        private const string DraftSessionKey = "PushBoxz.LevelEditor.Draft.v1";
        private const int MinSize = 1;
        private const int MaxSize = 40;
        private const int AutoGenerationStepBudget = 80;
        private const int AutoGenerationRollbackWindow = 8;
        private const int AutoGenerationGuardMultiplier = 12;

        private enum Brush
        {
            Floor,
            Wall,
            Goal,
            Box,
            Player,
            Erase
        }

        private enum AutoActionKind
        {
            Move,
            Pull
        }

        private readonly Color floorColor = new Color(0.72f, 0.74f, 0.68f);
        private readonly Color wallColor = new Color(0.28f, 0.31f, 0.35f);
        private readonly Color emptyColor = new Color(0.15f, 0.16f, 0.18f);
        private readonly Color goalColor = new Color(0.18f, 0.82f, 0.48f);
        private readonly Color boxColor = new Color(0.78f, 0.48f, 0.22f);
        private readonly Color playerColor = new Color(0.20f, 0.58f, 0.88f);
        private readonly Color gridLineColor = new Color(0f, 0f, 0f, 0.28f);

        private LevelDataAsset loadedAsset;
        private string levelId = "level_001";
        private int width = 5;
        private int height = 6;
        private BaseTileType[,] tiles;
        private readonly HashSet<Vector2Int> goals = new HashSet<Vector2Int>();
        private readonly HashSet<Vector2Int> boxes = new HashSet<Vector2Int>();
        private Vector2Int playerStart = Vector2Int.zero;
        private bool hasPlayer;
        private Direction editorPlayerFacing = Direction.Up;
        private bool reverseDesignMode = true;
        private Brush activeBrush = Brush.Floor;
        private Vector2 scrollPosition;
        private string lastMessage;
        private MessageType lastMessageType = MessageType.Info;
        private int autoWidth = 8;
        private int autoHeight = 8;
        private int autoBoxCount = 2;
        private int autoReverseStepCount = 18;
        private float autoInitialWallDensity = 0.08f;
        private float autoUnvisitedWallChance = 0.18f;
        private float autoContinueWeight = 4f;
        private float autoChangeDirectionWeight = 3f;
        private float autoChangeBoxWeight = 2f;
        private int autoSeed;
        private bool autoUseRandomSeed = true;
        private int solutionPlaybackIndex = -1;
        private Vector2Int playbackStartPlayer;
        private readonly List<Vector2Int> playbackStartBoxes = new List<Vector2Int>();
        private readonly List<AutoGeneratedAction> generatedReverseActions = new List<AutoGeneratedAction>();

        private struct AutoGeneratedAction
        {
            public AutoActionKind kind;
            public int boxId;
            public Direction direction;
            public Vector2Int playerFrom;
            public Vector2Int playerTo;
            public Vector2Int boxFrom;
            public Vector2Int boxTo;
        }

        private struct AutoGenerationSnapshot
        {
            public int actionCount;
            public int currentBoxIndex;
            public Vector2Int playerPosition;
            public Direction pullDirection;
            public List<Vector2Int> boxStates;
            public HashSet<Vector2Int> visited;
        }

        [Serializable]
        private class DraftState
        {
            public string assetPath;
            public string levelId;
            public int width;
            public int height;
            public int playerX;
            public int playerY;
            public bool hasPlayer;
            public int playerFacing;
            public bool hasReverseDesignMode;
            public bool reverseDesignMode;
            public int activeBrush;
            public List<TileDraft> tiles = new List<TileDraft>();
            public List<BoxDraft> boxes = new List<BoxDraft>();
            public List<ActionDraft> generatedActions = new List<ActionDraft>();
            public List<BoxDraft> playbackStartBoxes = new List<BoxDraft>();
            public int playbackStartPlayerX;
            public int playbackStartPlayerY;
            public int solutionPlaybackIndex;
        }

        [Serializable]
        private class TileDraft
        {
            public int x;
            public int y;
            public BaseTileType baseType;
            public bool hasGoal;
        }

        [Serializable]
        private class BoxDraft
        {
            public int x;
            public int y;
        }

        [Serializable]
        private class ActionDraft
        {
            public int kind;
            public int boxId;
            public int direction;
            public int playerFromX;
            public int playerFromY;
            public int playerToX;
            public int playerToY;
            public int boxFromX;
            public int boxFromY;
            public int boxToX;
            public int boxToY;
        }

        [MenuItem("Tools/PushBoxz/Level Editor")]
        public static void ShowWindow()
        {
            var window = GetWindow<PushBoxzLevelEditorWindow>("PushBoxz 关卡编辑器");
            window.minSize = new Vector2(560f, 480f);
            window.EnsureGrid();
            window.Show();
        }

        private void OnEnable()
        {
            if (!RestoreDraftState())
            {
                EnsureGrid();
            }
        }

        private void OnDisable()
        {
            SaveDraftState();
        }

        private void OnGUI()
        {
            EnsureGrid();
            HandleReverseDesignInput();

            EditorGUILayout.Space(8f);
            DrawAssetBar();
            EditorGUILayout.Space(6f);
            DrawMetadata();
            EditorGUILayout.Space(6f);
            DrawToolbar();
            EditorGUILayout.Space(6f);
            DrawAutoGenerationPanel();
            EditorGUILayout.Space(6f);
            DrawValidationPanel();
            EditorGUILayout.Space(8f);
            DrawGrid();
            EditorGUILayout.Space(8f);
            DrawActions();
            SaveDraftState();
        }

        private void DrawAssetBar()
        {
            EditorGUILayout.LabelField("关卡资源", EditorStyles.boldLabel);
            using (new EditorGUILayout.HorizontalScope())
            {
                var nextAsset = (LevelDataAsset)EditorGUILayout.ObjectField(loadedAsset, typeof(LevelDataAsset), false);
                if (nextAsset != loadedAsset)
                {
                    loadedAsset = nextAsset;
                    if (loadedAsset != null)
                    {
                        LoadFromAsset(loadedAsset);
                    }
                }

                if (GUILayout.Button("加载", GUILayout.Width(72f)))
                {
                    if (loadedAsset == null)
                    {
                        SetMessage("请先指定一个 LevelDataAsset 再加载。", MessageType.Warning);
                    }
                    else
                    {
                        LoadFromAsset(loadedAsset);
                    }
                }

                if (GUILayout.Button("新建", GUILayout.Width(72f)))
                {
                    loadedAsset = null;
                    levelId = "level_001";
                    width = 5;
                    height = 6;
                    hasPlayer = false;
                    goals.Clear();
                    boxes.Clear();
                    ClearGeneratedSolution();
                    CreateFilledGrid(BaseTileType.Floor);
                    SaveDraftState();
                    SetMessage("已创建新的关卡草稿。", MessageType.Info);
                }
            }
        }

        private void DrawMetadata()
        {
            EditorGUILayout.LabelField("关卡信息", EditorStyles.boldLabel);
            levelId = EditorGUILayout.TextField("关卡 ID", levelId);

            using (new EditorGUILayout.HorizontalScope())
            {
                var nextWidth = Mathf.Clamp(EditorGUILayout.IntField("宽度", width), MinSize, MaxSize);
                var nextHeight = Mathf.Clamp(EditorGUILayout.IntField("高度", height), MinSize, MaxSize);
                if (nextWidth != width || nextHeight != height)
                {
                    ResizeGrid(nextWidth, nextHeight);
                    SaveDraftState();
                }
            }
        }

        private void DrawToolbar()
        {
            EditorGUILayout.LabelField("画笔", EditorStyles.boldLabel);
            activeBrush = (Brush)GUILayout.Toolbar((int)activeBrush, Enum.GetNames(typeof(Brush)));
            EditorGUILayout.HelpBox("点击格子进行绘制。目的地可以和箱子或玩家初始点在同一格。墙会清空该格所有对象。Erase 会清除对象/目的地，并保留普通 Floor。", MessageType.None);

            EditorGUI.BeginChangeCheck();
            reverseDesignMode = EditorGUILayout.ToggleLeft("倒推设计模式", reverseDesignMode);
            if (EditorGUI.EndChangeCheck())
            {
                GUI.FocusControl(null);
                SaveDraftState();
                Repaint();
            }

            if (reverseDesignMode)
            {
                EditorGUILayout.HelpBox("倒推模式：点击网格让窗口获得焦点，然后用 WASD 移动编辑器内的玩家并改变朝向。当玩家正前方有箱子时按 F，玩家和箱子会一起向玩家身后一格倒退。", MessageType.Info);
            }
        }

        private void DrawAutoGenerationPanel()
        {
            EditorGUILayout.LabelField("自动生成", EditorStyles.boldLabel);
            using (new EditorGUILayout.HorizontalScope())
            {
                autoWidth = Mathf.Clamp(EditorGUILayout.IntField("宽度", autoWidth), MinSize, MaxSize);
                autoHeight = Mathf.Clamp(EditorGUILayout.IntField("高度", autoHeight), MinSize, MaxSize);
            }

            using (new EditorGUILayout.HorizontalScope())
            {
                autoBoxCount = Mathf.Clamp(EditorGUILayout.IntField("箱子/目的地", autoBoxCount), 1, Mathf.Max(1, autoWidth * autoHeight / 2));
                using (new EditorGUI.DisabledScope(true))
                {
                    autoReverseStepCount = AutoGenerationStepBudget;
                    EditorGUILayout.IntField("倒推步长", autoReverseStepCount);
                }
            }

            autoInitialWallDensity = EditorGUILayout.Slider("初始墙密度", autoInitialWallDensity, 0f, 0.45f);
            autoUnvisitedWallChance = EditorGUILayout.Slider("未走过格子成墙概率", autoUnvisitedWallChance, 0f, 0.75f);

            using (new EditorGUILayout.HorizontalScope())
            {
                autoContinueWeight = Mathf.Max(0f, EditorGUILayout.FloatField("继续拉权重", autoContinueWeight));
                autoChangeDirectionWeight = Mathf.Max(0f, EditorGUILayout.FloatField("换方向权重", autoChangeDirectionWeight));
                autoChangeBoxWeight = Mathf.Max(0f, EditorGUILayout.FloatField("换箱子权重", autoChangeBoxWeight));
            }

            using (new EditorGUILayout.HorizontalScope())
            {
                autoUseRandomSeed = EditorGUILayout.ToggleLeft("随机种子", autoUseRandomSeed, GUILayout.Width(86f));
                using (new EditorGUI.DisabledScope(autoUseRandomSeed))
                {
                    autoSeed = EditorGUILayout.IntField("Seed", autoSeed);
                }
            }

            using (new EditorGUILayout.HorizontalScope())
            {
                if (GUILayout.Button("生成倒推关卡", GUILayout.Height(28f)))
                {
                    GenerateRandomReverseLevel();
                }

                GUI.enabled = generatedReverseActions.Count > 0;
                if (GUILayout.Button("播放下一步解法", GUILayout.Height(28f)))
                {
                    PlayNextGeneratedSolutionStep();
                }

                if (GUILayout.Button("重置播放", GUILayout.Height(28f)))
                {
                    ResetGeneratedSolutionPlayback();
                }

                GUI.enabled = true;
            }

            if (generatedReverseActions.Count > 0)
            {
                var played = solutionPlaybackIndex < 0 ? 0 : solutionPlaybackIndex;
                EditorGUILayout.HelpBox("已记录倒推动作：" + generatedReverseActions.Count + "。解法播放进度：" + played + "/" + generatedReverseActions.Count + "。", MessageType.Info);
            }
        }

        private void DrawValidationPanel()
        {
            var issues = ValidateCurrentLevel();
            if (!string.IsNullOrEmpty(lastMessage))
            {
                EditorGUILayout.HelpBox(lastMessage, lastMessageType);
            }

            if (issues.Count == 0)
            {
                EditorGUILayout.HelpBox("校验通过。", MessageType.Info);
                return;
            }

            foreach (var issue in issues)
            {
                EditorGUILayout.HelpBox(issue, MessageType.Warning);
            }
        }

        private void DrawGrid()
        {
            EditorGUILayout.LabelField("网格", EditorStyles.boldLabel);

            var availableWidth = Mathf.Max(260f, position.width - 44f);
            var cellSize = Mathf.Clamp(Mathf.Floor(availableWidth / Mathf.Max(1, width)), 22f, 48f);
            var gridWidth = cellSize * width;
            var gridHeight = cellSize * height;

            scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition, GUILayout.MinHeight(Mathf.Min(gridHeight + 24f, 420f)));
            var rect = GUILayoutUtility.GetRect(gridWidth, gridHeight, GUILayout.ExpandWidth(false), GUILayout.ExpandHeight(false));
            DrawGridBackground(rect, cellSize);
            HandleGridInput(rect, cellSize);
            EditorGUILayout.EndScrollView();
        }

        private void DrawGridBackground(Rect rect, float cellSize)
        {
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    var drawY = height - 1 - y;
                    var cellRect = new Rect(rect.x + x * cellSize, rect.y + drawY * cellSize, cellSize, cellSize);
                    EditorGUI.DrawRect(cellRect, GetTileColor(tiles[x, y]));
                    EditorGUI.DrawRect(new Rect(cellRect.x, cellRect.y, cellRect.width, 1f), gridLineColor);
                    EditorGUI.DrawRect(new Rect(cellRect.x, cellRect.y, 1f, cellRect.height), gridLineColor);

                    var position = new Vector2Int(x, y);
                    if (goals.Contains(position))
                    {
                        var goalRect = RectInset(cellRect, cellSize * 0.25f);
                        EditorGUI.DrawRect(goalRect, goalColor);
                    }

                    if (boxes.Contains(position))
                    {
                        var boxRect = RectInset(cellRect, cellSize * 0.18f);
                        EditorGUI.DrawRect(boxRect, boxColor);
                    }

                    if (hasPlayer && playerStart == position)
                    {
                        var playerRect = RectInset(cellRect, cellSize * 0.26f);
                        EditorGUI.DrawRect(playerRect, playerColor);
                    }

                    if (cellSize >= 30f)
                    {
                        var label = GetCellLabel(position);
                        if (!string.IsNullOrEmpty(label))
                        {
                            var labelStyle = new GUIStyle(EditorStyles.boldLabel)
                            {
                                alignment = TextAnchor.MiddleCenter,
                                normal = { textColor = Color.white }
                            };
                            GUI.Label(cellRect, label, labelStyle);
                        }
                    }
                }
            }

            EditorGUI.DrawRect(new Rect(rect.x, rect.yMax - 1f, rect.width, 1f), gridLineColor);
            EditorGUI.DrawRect(new Rect(rect.xMax - 1f, rect.y, 1f, rect.height), gridLineColor);
        }

        private void HandleGridInput(Rect rect, float cellSize)
        {
            var current = Event.current;
            if (current == null || current.type != EventType.MouseDown && current.type != EventType.MouseDrag)
            {
                return;
            }

            if (!rect.Contains(current.mousePosition) || current.button != 0)
            {
                return;
            }

            var x = Mathf.FloorToInt((current.mousePosition.x - rect.x) / cellSize);
            var drawY = Mathf.FloorToInt((current.mousePosition.y - rect.y) / cellSize);
            var y = height - 1 - drawY;
            if (x < 0 || y < 0 || x >= width || y >= height)
            {
                return;
            }

            PaintCell(new Vector2Int(x, y));
            SaveDraftState();
            current.Use();
            Repaint();
        }

        private void DrawActions()
        {
            using (new EditorGUILayout.HorizontalScope())
            {
                if (GUILayout.Button("保存 LevelDataAsset", GUILayout.Height(30f)))
                {
                    SaveLevel();
                }

                if (GUILayout.Button("生成场景预览", GUILayout.Height(30f)))
                {
                    GeneratePreviewInScene();
                }
            }
        }

        private void PaintCell(Vector2Int position)
        {
            ClearGeneratedSolution();
            switch (activeBrush)
            {
                case Brush.Floor:
                    tiles[position.x, position.y] = BaseTileType.Floor;
                    break;
                case Brush.Wall:
                    tiles[position.x, position.y] = BaseTileType.Wall;
                    goals.Remove(position);
                    boxes.Remove(position);
                    if (hasPlayer && playerStart == position)
                    {
                        hasPlayer = false;
                    }
                    break;
                case Brush.Goal:
                    tiles[position.x, position.y] = BaseTileType.Floor;
                    goals.Add(position);
                    break;
                case Brush.Box:
                    tiles[position.x, position.y] = BaseTileType.Floor;
                    if (hasPlayer && playerStart == position)
                    {
                        hasPlayer = false;
                    }
                    boxes.Add(position);
                    break;
                case Brush.Player:
                    tiles[position.x, position.y] = BaseTileType.Floor;
                    boxes.Remove(position);
                    playerStart = position;
                    hasPlayer = true;
                    editorPlayerFacing = Direction.Up;
                    break;
                case Brush.Erase:
                    tiles[position.x, position.y] = BaseTileType.Floor;
                    goals.Remove(position);
                    boxes.Remove(position);
                    if (hasPlayer && playerStart == position)
                    {
                        hasPlayer = false;
                    }
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        private void ClearGeneratedSolution()
        {
            generatedReverseActions.Clear();
            playbackStartBoxes.Clear();
            playbackStartPlayer = Vector2Int.zero;
            solutionPlaybackIndex = -1;
        }

        private void GenerateRandomReverseLevel()
        {
            var random = autoUseRandomSeed ? new System.Random(Environment.TickCount) : new System.Random(autoSeed);
            if (autoUseRandomSeed)
            {
                autoSeed = Environment.TickCount;
                random = new System.Random(autoSeed);
            }

            width = Mathf.Clamp(autoWidth, MinSize, MaxSize);
            height = Mathf.Clamp(autoHeight, MinSize, MaxSize);
            autoReverseStepCount = AutoGenerationStepBudget;
            levelId = "generated_" + autoSeed.ToString("X8").ToLowerInvariant();
            loadedAsset = null;
            hasPlayer = false;
            boxes.Clear();
            goals.Clear();
            generatedReverseActions.Clear();
            playbackStartBoxes.Clear();
            solutionPlaybackIndex = -1;
            CreateFilledGrid(BaseTileType.Floor);

            var totalCells = width * height;
            var requestedBoxes = Mathf.Clamp(autoBoxCount, 1, Mathf.Max(1, totalCells / 3));
            var boxStates = new List<Vector2Int>();
            var targetPositions = new List<Vector2Int>();
            var visited = new HashSet<Vector2Int>();
            var used = new HashSet<Vector2Int>();

            for (var i = 0; i < requestedBoxes; i++)
            {
                if (!TryGetRandomFreeCell(random, used, out var position))
                {
                    break;
                }

                used.Add(position);
                goals.Add(position);
                boxStates.Add(position);
                targetPositions.Add(position);
                visited.Add(position);
            }

            if (boxStates.Count == 0)
            {
                SetMessage("自动生成失败：没有足够空间放置箱子。", MessageType.Warning);
                return;
            }

            AddRandomInitialWalls(random, used);

            var currentBoxIndex = random.Next(boxStates.Count);
            if (!TryGetRandomStandSide(random, boxStates, targetPositions, currentBoxIndex, out var playerPosition, out var pullDirection))
            {
                SetMessage("自动生成失败：找不到可站立的初始箱子侧边。", MessageType.Warning);
                return;
            }

            if (!CanReachEveryGoal(playerPosition))
            {
                SetMessage("自动生成失败：玩家无法到达所有目的地，请重新生成。", MessageType.Warning);
                return;
            }

            visited.Add(playerPosition);
            var rollbackCount = 0;
            var snapshots = new List<AutoGenerationSnapshot>();
            var completedSteps = 0;
            var guardCount = 0;
            while (completedSteps < autoReverseStepCount && guardCount++ < autoReverseStepCount * AutoGenerationGuardMultiplier)
            {
                var snapshot = CreateAutoGenerationSnapshot(boxStates, visited, currentBoxIndex, playerPosition, pullDirection);
                var actionChoice = PickAutoAction(random);
                var acted = false;

                if (actionChoice == 2 && boxStates.Count > 1)
                {
                    acted = TryAutoSwitchBox(random, boxStates, targetPositions, visited, ref currentBoxIndex, ref playerPosition, out pullDirection);
                }

                if (!acted && actionChoice == 1)
                {
                    acted = TryAutoChangeDirection(random, boxStates, targetPositions, visited, currentBoxIndex, ref playerPosition, out pullDirection);
                }

                if (!acted)
                {
                    acted = TryAutoPullCurrentBox(boxStates, visited, currentBoxIndex, ref playerPosition, pullDirection);
                }

                if (!acted)
                {
                    acted = TryAutoChangeDirection(random, boxStates, targetPositions, visited, currentBoxIndex, ref playerPosition, out pullDirection)
                        || TryAutoSwitchBox(random, boxStates, targetPositions, visited, ref currentBoxIndex, ref playerPosition, out pullDirection);
                }

                if (!acted)
                {
                    if (TryRollbackAutoGeneration(random, snapshots, boxStates, ref visited, ref currentBoxIndex, ref playerPosition, ref pullDirection))
                    {
                        rollbackCount++;
                        completedSteps = Mathf.Max(0, completedSteps - 1);
                        continue;
                    }

                    break;
                }

                snapshots.Add(snapshot);
                if (snapshots.Count > AutoGenerationRollbackWindow)
                {
                    snapshots.RemoveAt(0);
                }

                completedSteps++;
            }

            FillUnvisitedWalls(random, visited, boxStates);

            playerStart = playerPosition;
            hasPlayer = true;
            boxes.Clear();
            for (var i = 0; i < boxStates.Count; i++)
            {
                boxes.Add(boxStates[i]);
            }

            playbackStartPlayer = playerStart;
            playbackStartBoxes.Clear();
            playbackStartBoxes.AddRange(boxStates);
            SaveDraftState();
            SetMessage("自动生成完成。Seed: " + autoSeed + "，回退：" + rollbackCount + "，倒推动作：" + generatedReverseActions.Count + "。", MessageType.Info);
            Repaint();
        }

        private bool CanReachEveryGoal(Vector2Int start)
        {
            if (!IsWalkable(start))
            {
                return false;
            }

            var reachable = new HashSet<Vector2Int>();
            var frontier = new Queue<Vector2Int>();
            reachable.Add(start);
            frontier.Enqueue(start);

            while (frontier.Count > 0)
            {
                var current = frontier.Dequeue();
                foreach (var next in GetNeighbors(current))
                {
                    if (reachable.Contains(next) || !IsWalkable(next))
                    {
                        continue;
                    }

                    reachable.Add(next);
                    frontier.Enqueue(next);
                }
            }

            foreach (var goal in goals)
            {
                if (!reachable.Contains(goal))
                {
                    return false;
                }
            }

            return true;
        }

        private AutoGenerationSnapshot CreateAutoGenerationSnapshot(
            List<Vector2Int> boxStates,
            HashSet<Vector2Int> visited,
            int currentBoxIndex,
            Vector2Int playerPosition,
            Direction pullDirection)
        {
            return new AutoGenerationSnapshot
            {
                actionCount = generatedReverseActions.Count,
                currentBoxIndex = currentBoxIndex,
                playerPosition = playerPosition,
                pullDirection = pullDirection,
                boxStates = new List<Vector2Int>(boxStates),
                visited = new HashSet<Vector2Int>(visited)
            };
        }

        private bool TryRollbackAutoGeneration(
            System.Random random,
            List<AutoGenerationSnapshot> snapshots,
            List<Vector2Int> boxStates,
            ref HashSet<Vector2Int> visited,
            ref int currentBoxIndex,
            ref Vector2Int playerPosition,
            ref Direction pullDirection)
        {
            if (snapshots.Count == 0)
            {
                return false;
            }

            var rollbackSteps = random.Next(1, Mathf.Min(AutoGenerationRollbackWindow, snapshots.Count) + 1);
            var snapshotIndex = snapshots.Count - rollbackSteps;
            var snapshot = snapshots[snapshotIndex];

            if (generatedReverseActions.Count > snapshot.actionCount)
            {
                generatedReverseActions.RemoveRange(snapshot.actionCount, generatedReverseActions.Count - snapshot.actionCount);
            }

            boxStates.Clear();
            boxStates.AddRange(snapshot.boxStates);
            visited = new HashSet<Vector2Int>(snapshot.visited);
            currentBoxIndex = snapshot.currentBoxIndex;
            playerPosition = snapshot.playerPosition;
            pullDirection = snapshot.pullDirection;
            snapshots.RemoveRange(snapshotIndex, snapshots.Count - snapshotIndex);
            return true;
        }

        private void AddRandomInitialWalls(System.Random random, HashSet<Vector2Int> reserved)
        {
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    var position = new Vector2Int(x, y);
                    if (reserved.Contains(position) || random.NextDouble() > autoInitialWallDensity)
                    {
                        continue;
                    }

                    tiles[x, y] = BaseTileType.Wall;
                }
            }
        }

        private void FillUnvisitedWalls(System.Random random, HashSet<Vector2Int> visited, List<Vector2Int> boxStates)
        {
            var protectedCells = new HashSet<Vector2Int>(visited);
            for (var i = 0; i < boxStates.Count; i++)
            {
                protectedCells.Add(boxStates[i]);
            }

            foreach (var goal in goals)
            {
                protectedCells.Add(goal);
            }

            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    var position = new Vector2Int(x, y);
                    if (protectedCells.Contains(position) || tiles[x, y] == BaseTileType.Wall)
                    {
                        continue;
                    }

                    if (random.NextDouble() <= autoUnvisitedWallChance)
                    {
                        tiles[x, y] = BaseTileType.Wall;
                    }
                }
            }
        }

        private int PickAutoAction(System.Random random)
        {
            var total = autoContinueWeight + autoChangeDirectionWeight + autoChangeBoxWeight;
            if (total <= 0f)
            {
                return 0;
            }

            var roll = random.NextDouble() * total;
            if (roll < autoContinueWeight)
            {
                return 0;
            }

            roll -= autoContinueWeight;
            return roll < autoChangeDirectionWeight ? 1 : 2;
        }

        private bool TryAutoPullCurrentBox(List<Vector2Int> boxStates, HashSet<Vector2Int> visited, int boxIndex, ref Vector2Int playerPosition, Direction pullDirection)
        {
            var offset = DirectionUtility.ToOffset(pullDirection);
            var boxPosition = boxStates[boxIndex];
            if (playerPosition != boxPosition - offset)
            {
                return false;
            }

            var playerTarget = playerPosition - offset;
            if (!CanAutoOccupy(playerTarget, boxStates))
            {
                return false;
            }

            var action = new AutoGeneratedAction
            {
                kind = AutoActionKind.Pull,
                boxId = boxIndex,
                direction = pullDirection,
                playerFrom = playerPosition,
                playerTo = playerTarget,
                boxFrom = boxPosition,
                boxTo = playerPosition
            };

            boxStates[boxIndex] = playerPosition;
            playerPosition = playerTarget;
            visited.Add(action.playerFrom);
            visited.Add(action.playerTo);
            visited.Add(action.boxFrom);
            visited.Add(action.boxTo);
            generatedReverseActions.Add(action);
            return true;
        }

        private bool TryAutoChangeDirection(System.Random random, List<Vector2Int> boxStates, List<Vector2Int> targetPositions, HashSet<Vector2Int> visited, int boxIndex, ref Vector2Int playerPosition, out Direction pullDirection)
        {
            pullDirection = Direction.Up;
            var options = GetStandOptions(boxStates, boxIndex);
            SortStandOptionsByTargetDistance(random, options, boxStates, targetPositions, boxIndex);
            for (var i = 0; i < options.Count; i++)
            {
                var option = options[i];
                if (option.position == playerPosition)
                {
                    continue;
                }

                if (!TryFindPath(playerPosition, option.position, boxStates, out var path))
                {
                    continue;
                }

                if (!CanAutoPullFromStand(boxStates, boxIndex, option))
                {
                    continue;
                }

                AppendMovePath(path, visited);
                playerPosition = option.position;
                pullDirection = option.direction;
                return TryAutoPullCurrentBox(boxStates, visited, boxIndex, ref playerPosition, pullDirection);
            }

            return false;
        }

        private bool TryAutoSwitchBox(System.Random random, List<Vector2Int> boxStates, List<Vector2Int> targetPositions, HashSet<Vector2Int> visited, ref int currentBoxIndex, ref Vector2Int playerPosition, out Direction pullDirection)
        {
            pullDirection = Direction.Up;
            var indices = new List<int>();
            for (var i = 0; i < boxStates.Count; i++)
            {
                if (i != currentBoxIndex)
                {
                    indices.Add(i);
                }
            }

            Shuffle(random, indices);
            for (var i = 0; i < indices.Count; i++)
            {
                var nextBox = indices[i];
                var options = GetStandOptions(boxStates, nextBox);
                SortStandOptionsByTargetDistance(random, options, boxStates, targetPositions, nextBox);
                for (var j = 0; j < options.Count; j++)
                {
                    var option = options[j];
                    if (!TryFindPath(playerPosition, option.position, boxStates, out var path))
                    {
                        continue;
                    }

                    if (!CanAutoPullFromStand(boxStates, nextBox, option))
                    {
                        continue;
                    }

                    AppendMovePath(path, visited);
                    currentBoxIndex = nextBox;
                    playerPosition = option.position;
                    pullDirection = option.direction;
                    return TryAutoPullCurrentBox(boxStates, visited, currentBoxIndex, ref playerPosition, pullDirection);
                }
            }

            return false;
        }

        private void AppendMovePath(List<Vector2Int> path, HashSet<Vector2Int> visited)
        {
            for (var i = 1; i < path.Count; i++)
            {
                var from = path[i - 1];
                var to = path[i];
                generatedReverseActions.Add(new AutoGeneratedAction
                {
                    kind = AutoActionKind.Move,
                    boxId = -1,
                    direction = DirectionFromOffset(to - from),
                    playerFrom = from,
                    playerTo = to,
                    boxFrom = Vector2Int.zero,
                    boxTo = Vector2Int.zero
                });
                visited.Add(from);
                visited.Add(to);
            }
        }

        private List<StandOption> GetStandOptions(List<Vector2Int> boxStates, int boxIndex)
        {
            var options = new List<StandOption>();
            var boxPosition = boxStates[boxIndex];
            AddStandOption(options, boxStates, boxPosition, Direction.Up);
            AddStandOption(options, boxStates, boxPosition, Direction.Down);
            AddStandOption(options, boxStates, boxPosition, Direction.Left);
            AddStandOption(options, boxStates, boxPosition, Direction.Right);
            return options;
        }

        private void AddStandOption(List<StandOption> options, List<Vector2Int> boxStates, Vector2Int boxPosition, Direction direction)
        {
            var offset = DirectionUtility.ToOffset(direction);
            var stand = boxPosition - offset;
            var option = new StandOption { position = stand, direction = direction };
            if (CanAutoOccupy(stand, boxStates) && CanAutoPullFromStand(boxStates, boxPosition, option))
            {
                options.Add(option);
            }
        }

        private bool CanAutoPullFromStand(List<Vector2Int> boxStates, int boxIndex, StandOption option)
        {
            return boxIndex >= 0
                && boxIndex < boxStates.Count
                && CanAutoPullFromStand(boxStates, boxStates[boxIndex], option);
        }

        private bool CanAutoPullFromStand(List<Vector2Int> boxStates, Vector2Int boxPosition, StandOption option)
        {
            var offset = DirectionUtility.ToOffset(option.direction);
            return option.position == boxPosition - offset
                && CanAutoOccupy(option.position - offset, boxStates);
        }

        private void SortStandOptionsByTargetDistance(System.Random random, List<StandOption> options, List<Vector2Int> boxStates, List<Vector2Int> targetPositions, int boxIndex)
        {
            Shuffle(random, options);
            options.Sort((left, right) =>
                GetAutoPullDistanceScore(boxStates, targetPositions, boxIndex, right)
                    .CompareTo(GetAutoPullDistanceScore(boxStates, targetPositions, boxIndex, left)));
        }

        private int GetAutoPullDistanceScore(List<Vector2Int> boxStates, List<Vector2Int> targetPositions, int boxIndex, StandOption option)
        {
            if (boxIndex < 0 || boxIndex >= boxStates.Count || boxIndex >= targetPositions.Count)
            {
                return 0;
            }

            var target = targetPositions[boxIndex];
            var nextBoxPosition = option.position;
            var dx = nextBoxPosition.x - target.x;
            var dy = nextBoxPosition.y - target.y;
            return dx * dx + dy * dy;
        }

        private bool TryGetRandomStandSide(System.Random random, List<Vector2Int> boxStates, List<Vector2Int> targetPositions, int boxIndex, out Vector2Int playerPosition, out Direction pullDirection)
        {
            var options = GetStandOptions(boxStates, boxIndex);
            if (options.Count == 0)
            {
                playerPosition = Vector2Int.zero;
                pullDirection = Direction.Up;
                return false;
            }

            SortStandOptionsByTargetDistance(random, options, boxStates, targetPositions, boxIndex);
            var option = options[0];
            playerPosition = option.position;
            pullDirection = option.direction;
            return true;
        }

        private bool TryFindPath(Vector2Int start, Vector2Int target, List<Vector2Int> boxStates, out List<Vector2Int> path)
        {
            path = new List<Vector2Int>();
            if (start == target)
            {
                path.Add(start);
                return true;
            }

            var frontier = new Queue<Vector2Int>();
            var cameFrom = new Dictionary<Vector2Int, Vector2Int>();
            frontier.Enqueue(start);
            cameFrom[start] = start;

            while (frontier.Count > 0)
            {
                var current = frontier.Dequeue();
                foreach (var next in GetNeighbors(current))
                {
                    if (cameFrom.ContainsKey(next) || !CanAutoOccupy(next, boxStates))
                    {
                        continue;
                    }

                    cameFrom[next] = current;
                    if (next == target)
                    {
                        BuildPath(cameFrom, start, target, path);
                        return true;
                    }

                    frontier.Enqueue(next);
                }
            }

            return false;
        }

        private static void BuildPath(Dictionary<Vector2Int, Vector2Int> cameFrom, Vector2Int start, Vector2Int target, List<Vector2Int> path)
        {
            var current = target;
            path.Add(current);
            while (current != start)
            {
                current = cameFrom[current];
                path.Add(current);
            }

            path.Reverse();
        }

        private IEnumerable<Vector2Int> GetNeighbors(Vector2Int position)
        {
            yield return position + Vector2Int.up;
            yield return position + Vector2Int.down;
            yield return position + Vector2Int.left;
            yield return position + Vector2Int.right;
        }

        private bool CanAutoOccupy(Vector2Int position, List<Vector2Int> boxStates)
        {
            return IsWalkable(position) && !boxStates.Contains(position);
        }

        private bool TryGetRandomFreeCell(System.Random random, HashSet<Vector2Int> used, out Vector2Int position)
        {
            var candidates = new List<Vector2Int>();
            for (var y = 0; y < autoHeight; y++)
            {
                for (var x = 0; x < autoWidth; x++)
                {
                    var candidate = new Vector2Int(x, y);
                    if (!used.Contains(candidate))
                    {
                        candidates.Add(candidate);
                    }
                }
            }

            if (candidates.Count == 0)
            {
                position = Vector2Int.zero;
                return false;
            }

            position = candidates[random.Next(candidates.Count)];
            return true;
        }

        private void ResetGeneratedSolutionPlayback()
        {
            if (generatedReverseActions.Count == 0 || playbackStartBoxes.Count == 0)
            {
                return;
            }

            playerStart = playbackStartPlayer;
            hasPlayer = true;
            boxes.Clear();
            for (var i = 0; i < playbackStartBoxes.Count; i++)
            {
                boxes.Add(playbackStartBoxes[i]);
            }

            solutionPlaybackIndex = 0;
            SaveDraftState();
            SetMessage("已重置解法播放。", MessageType.Info);
            Repaint();
        }

        private void PlayNextGeneratedSolutionStep()
        {
            if (generatedReverseActions.Count == 0)
            {
                return;
            }

            if (solutionPlaybackIndex < 0)
            {
                ResetGeneratedSolutionPlayback();
            }

            if (solutionPlaybackIndex >= generatedReverseActions.Count)
            {
                SetMessage("解法播放已完成。", MessageType.Info);
                return;
            }

            var action = generatedReverseActions[generatedReverseActions.Count - 1 - solutionPlaybackIndex];
            if (action.kind == AutoActionKind.Move)
            {
                playerStart = action.playerFrom;
                editorPlayerFacing = OppositeDirection(action.direction);
            }
            else
            {
                boxes.Remove(action.boxTo);
                boxes.Add(action.boxFrom);
                playerStart = action.boxTo;
                editorPlayerFacing = action.direction;
            }

            hasPlayer = true;
            solutionPlaybackIndex++;
            SaveDraftState();
            SetMessage("播放解法步骤 " + solutionPlaybackIndex + "/" + generatedReverseActions.Count + "。", MessageType.Info);
            Repaint();
        }

        private static Direction DirectionFromOffset(Vector2Int offset)
        {
            if (offset == Vector2Int.up)
            {
                return Direction.Up;
            }

            if (offset == Vector2Int.down)
            {
                return Direction.Down;
            }

            if (offset == Vector2Int.left)
            {
                return Direction.Left;
            }

            return Direction.Right;
        }

        private static Direction OppositeDirection(Direction direction)
        {
            switch (direction)
            {
                case Direction.Up:
                    return Direction.Down;
                case Direction.Down:
                    return Direction.Up;
                case Direction.Left:
                    return Direction.Right;
                case Direction.Right:
                    return Direction.Left;
                default:
                    return Direction.Up;
            }
        }

        private static void Shuffle<T>(System.Random random, List<T> list)
        {
            for (var i = list.Count - 1; i > 0; i--)
            {
                var j = random.Next(i + 1);
                (list[i], list[j]) = (list[j], list[i]);
            }
        }

        private struct StandOption
        {
            public Vector2Int position;
            public Direction direction;
        }

        private List<LevelSolutionStep> BuildForwardSolutionSteps()
        {
            var steps = new List<LevelSolutionStep>();
            for (var i = generatedReverseActions.Count - 1; i >= 0; i--)
            {
                var action = generatedReverseActions[i];
                if (action.kind == AutoActionKind.Move)
                {
                    steps.Add(new LevelSolutionStep
                    {
                        kind = LevelSolutionStepKind.Move,
                        boxId = -1,
                        direction = OppositeDirection(action.direction),
                        playerFrom = action.playerTo,
                        playerTo = action.playerFrom,
                        boxFrom = Vector2Int.zero,
                        boxTo = Vector2Int.zero
                    });
                    continue;
                }

                steps.Add(new LevelSolutionStep
                {
                    kind = LevelSolutionStepKind.Push,
                    boxId = action.boxId,
                    direction = action.direction,
                    playerFrom = action.playerTo,
                    playerTo = action.boxTo,
                    boxFrom = action.boxTo,
                    boxTo = action.boxFrom
                });
            }

            return steps;
        }

        private void RestoreGeneratedActionsFromSolution(LevelDataAsset asset)
        {
            generatedReverseActions.Clear();
            playbackStartBoxes.Clear();
            playbackStartPlayer = playerStart;
            solutionPlaybackIndex = -1;

            if (asset.solutionSteps == null || asset.solutionSteps.Count == 0)
            {
                return;
            }

            foreach (var box in boxes)
            {
                playbackStartBoxes.Add(box);
            }

            for (var i = asset.solutionSteps.Count - 1; i >= 0; i--)
            {
                var step = asset.solutionSteps[i];
                if (step == null)
                {
                    continue;
                }

                if (step.kind == LevelSolutionStepKind.Move)
                {
                    generatedReverseActions.Add(new AutoGeneratedAction
                    {
                        kind = AutoActionKind.Move,
                        boxId = -1,
                        direction = OppositeDirection(step.direction),
                        playerFrom = step.playerTo,
                        playerTo = step.playerFrom,
                        boxFrom = Vector2Int.zero,
                        boxTo = Vector2Int.zero
                    });
                    continue;
                }

                generatedReverseActions.Add(new AutoGeneratedAction
                {
                    kind = AutoActionKind.Pull,
                    boxId = step.boxId,
                    direction = step.direction,
                    playerFrom = step.playerTo,
                    playerTo = step.playerFrom,
                    boxFrom = step.boxTo,
                    boxTo = step.boxFrom
                });
            }
        }

        private void SaveLevel()
        {
            var issues = ValidateCurrentLevel();
            if (issues.Count > 0)
            {
                SetMessage("请先修复校验问题，再保存关卡。", MessageType.Warning);
                return;
            }

            EnsureLevelsFolder();

            var asset = loadedAsset;
            if (asset == null)
            {
                var path = AssetDatabase.GenerateUniqueAssetPath((LevelsFolder + "/" + SanitizeFileName(levelId) + ".asset").Replace("\\", "/"));
                asset = CreateInstance<LevelDataAsset>();
                AssetDatabase.CreateAsset(asset, path);
                loadedAsset = asset;
            }

            ApplyToAsset(asset);
            var renameError = TryRenameAssetToLevelId(asset);
            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            PushBoxzLevelCatalogBuilder.RebuildCatalogAsset();
            Selection.activeObject = asset;
            if (string.IsNullOrEmpty(renameError))
            {
                SetMessage("已保存关卡资源：" + AssetDatabase.GetAssetPath(asset), MessageType.Info);
            }
            else
            {
                SetMessage("已保存关卡资源，但自动重命名失败：" + renameError, MessageType.Warning);
            }
        }

        private void GeneratePreviewInScene()
        {
            var issues = ValidateCurrentLevel();
            if (issues.Count > 0)
            {
                SetMessage("请先修复校验问题，再生成预览。", MessageType.Warning);
                return;
            }

            if (loadedAsset == null)
            {
                SaveLevel();
                if (loadedAsset == null)
                {
                    SetMessage("请先保存关卡，再生成可试玩预览。", MessageType.Warning);
                    return;
                }
            }

            ApplyToAsset(loadedAsset);
            EditorUtility.SetDirty(loadedAsset);
            AssetDatabase.SaveAssets();

            GeneratePlayablePreview(loadedAsset);
            SetMessage("已生成可试玩预览。进入 Play Mode 后使用 WASD / F 进行测试。", MessageType.Info);
        }

        private void GeneratePlayablePreview(LevelDataAsset asset)
        {
            var host = GameObject.Find("PushBoxz Runtime Host");
            if (host == null)
            {
                host = new GameObject("PushBoxz Runtime Host");
            }

            var builder = host.GetComponent<LevelSceneBuilder>();
            if (builder == null)
            {
                builder = host.AddComponent<LevelSceneBuilder>();
            }

            var session = host.GetComponent<GameSession>();
            if (session == null)
            {
                session = host.AddComponent<GameSession>();
            }

            var input = host.GetComponent<PlayerInputController>();
            if (input == null)
            {
                input = host.AddComponent<PlayerInputController>();
            }

            var hud = host.GetComponent<RuntimeHud>();
            if (hud == null)
            {
                hud = host.AddComponent<RuntimeHud>();
            }

            session.LevelData = asset;
            builder.Build(asset);

            EditorUtility.SetDirty(host);
            EditorUtility.SetDirty(builder);
            EditorUtility.SetDirty(session);
            EditorUtility.SetDirty(input);
            EditorUtility.SetDirty(hud);
            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        }

        private void HandleReverseDesignInput()
        {
            if (!reverseDesignMode || EditorGUIUtility.editingTextField)
            {
                return;
            }

            var current = Event.current;
            if (current == null || current.type != EventType.KeyDown)
            {
                return;
            }

            var handled = true;
            switch (current.keyCode)
            {
                case KeyCode.W:
                    TryReverseModeMove(Direction.Up);
                    break;
                case KeyCode.S:
                    TryReverseModeMove(Direction.Down);
                    break;
                case KeyCode.A:
                    TryReverseModeMove(Direction.Left);
                    break;
                case KeyCode.D:
                    TryReverseModeMove(Direction.Right);
                    break;
                case KeyCode.F:
                    TryReverseModePull();
                    break;
                default:
                    handled = false;
                    break;
            }

            if (!handled)
            {
                return;
            }

            SaveDraftState();
            current.Use();
            Repaint();
        }

        private void TryReverseModeMove(Direction direction)
        {
            editorPlayerFacing = direction;

            if (!hasPlayer)
            {
                SetMessage("倒推模式需要一个玩家初始点。", MessageType.Warning);
                return;
            }

            var target = playerStart + DirectionUtility.ToOffset(direction);
            if (!CanEditorPlayerOccupy(target))
            {
                SetMessage("倒推移动被阻挡：" + FormatPosition(target) + "。", MessageType.Info);
                return;
            }

            ClearGeneratedSolution();
            playerStart = target;
            SetMessage("倒推模式：玩家移动到 " + FormatPosition(playerStart) + "。", MessageType.Info);
        }

        private void TryReverseModePull()
        {
            if (!hasPlayer)
            {
                SetMessage("倒推模式需要一个玩家初始点。", MessageType.Warning);
                return;
            }

            var facingOffset = DirectionUtility.ToOffset(editorPlayerFacing);
            var boxPosition = playerStart + facingOffset;
            var playerTarget = playerStart - facingOffset;

            if (!boxes.Contains(boxPosition))
            {
                SetMessage("倒拉失败：玩家正前方没有箱子。", MessageType.Info);
                return;
            }

            if (!CanEditorPlayerOccupy(playerTarget))
            {
                SetMessage("倒拉失败：玩家身后一格被阻挡 " + FormatPosition(playerTarget) + "。", MessageType.Info);
                return;
            }

            ClearGeneratedSolution();
            boxes.Remove(boxPosition);
            boxes.Add(playerStart);
            playerStart = playerTarget;
            SetMessage("倒拉成功：箱子移动到 " + FormatPosition(playerStart + facingOffset) + "。", MessageType.Info);
        }

        private void LoadFromAsset(LevelDataAsset asset)
        {
            levelId = asset.levelId;
            width = Mathf.Clamp(asset.width, MinSize, MaxSize);
            height = Mathf.Clamp(asset.height, MinSize, MaxSize);
            goals.Clear();
            CreateFilledGrid(BaseTileType.Floor);

            if (asset.cells != null)
            {
                foreach (var cell in asset.cells)
                {
                    if (cell == null || cell.x < 0 || cell.y < 0 || cell.x >= width || cell.y >= height)
                    {
                        continue;
                    }

                    tiles[cell.x, cell.y] = cell.baseType;
                    if (cell.hasGoal)
                    {
                        goals.Add(new Vector2Int(cell.x, cell.y));
                    }
                }
            }

            boxes.Clear();
            if (asset.boxStarts != null)
            {
                foreach (var box in asset.boxStarts)
                {
                    if (box.x >= 0 && box.y >= 0 && box.x < width && box.y < height)
                    {
                        boxes.Add(box);
                    }
                }
            }

            playerStart = asset.playerStart;
            hasPlayer = playerStart.x >= 0 && playerStart.y >= 0 && playerStart.x < width && playerStart.y < height;
            editorPlayerFacing = Direction.Up;
            RestoreGeneratedActionsFromSolution(asset);
            SetMessage("已加载关卡资源：" + AssetDatabase.GetAssetPath(asset), MessageType.Info);
            SaveDraftState();
            Repaint();
        }

        private void ApplyToAsset(LevelDataAsset asset)
        {
            var usePlaybackStart = generatedReverseActions.Count > 0 && playbackStartBoxes.Count > 0 && solutionPlaybackIndex >= 0;
            var assetPlayerStart = usePlaybackStart ? playbackStartPlayer : playerStart;
            var assetBoxes = usePlaybackStart ? (IEnumerable<Vector2Int>)playbackStartBoxes : boxes;

            asset.levelId = levelId.Trim();
            asset.width = width;
            asset.height = height;
            asset.playerStart = assetPlayerStart;

            asset.cells = new List<TileCell>(width * height);
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    asset.cells.Add(new TileCell(x, y, tiles[x, y], goals.Contains(new Vector2Int(x, y))));
                }
            }

            asset.boxStarts = assetBoxes.OrderBy(b => b.y).ThenBy(b => b.x).ToList();
            asset.solutionSteps = BuildForwardSolutionSteps();
        }

        private string TryRenameAssetToLevelId(LevelDataAsset asset)
        {
            var assetPath = AssetDatabase.GetAssetPath(asset);
            if (string.IsNullOrEmpty(assetPath))
            {
                return string.Empty;
            }

            var targetName = SanitizeFileName(asset.levelId);
            if (Path.GetFileNameWithoutExtension(assetPath) == targetName)
            {
                asset.name = targetName;
                return string.Empty;
            }

            var error = AssetDatabase.RenameAsset(assetPath, targetName);
            if (string.IsNullOrEmpty(error))
            {
                asset.name = targetName;
            }

            return error;
        }

        private List<string> ValidateCurrentLevel()
        {
            var issues = new List<string>();
            if (string.IsNullOrWhiteSpace(levelId))
            {
                issues.Add("错误：关卡 ID 不能为空。");
            }

            if (width < MinSize || height < MinSize)
            {
                issues.Add("错误：宽度和高度至少为 1。");
            }

            if (!hasPlayer)
            {
                issues.Add("错误：必须且只能有一个玩家初始点。");
            }
            else if (!IsInside(playerStart))
            {
                issues.Add("错误：玩家初始点超出关卡范围。");
            }
            else if (!IsWalkable(playerStart))
            {
                issues.Add("错误：玩家初始点必须在 Floor 格子上。");
            }

            if (boxes.Count == 0)
            {
                issues.Add("错误：至少需要一个箱子。");
            }

            if (goals.Count == 0)
            {
                issues.Add("错误：至少需要一个目的地。");
            }

            if (boxes.Count != goals.Count)
            {
                issues.Add("错误：箱子数量必须等于目的地数量。箱子：" + boxes.Count + "，目的地：" + goals.Count + "。");
            }

            foreach (var box in boxes)
            {
                if (!IsInside(box))
                {
                    issues.Add("错误：箱子超出关卡范围 " + FormatPosition(box) + "。");
                }
                else if (!IsWalkable(box))
                {
                    issues.Add("错误：箱子必须在 Floor 格子上 " + FormatPosition(box) + "。");
                }
            }

            foreach (var goal in goals)
            {
                if (!IsInside(goal))
                {
                    issues.Add("错误：目的地超出关卡范围 " + FormatPosition(goal) + "。");
                }
                else if (!IsWalkable(goal))
                {
                    issues.Add("错误：目的地必须在 Floor 格子上 " + FormatPosition(goal) + "。");
                }
            }

            if (hasPlayer && boxes.Contains(playerStart))
            {
                issues.Add("错误：玩家和箱子不能在同一格。");
            }

            if (!string.IsNullOrWhiteSpace(levelId) && FindExistingAssetByLevelId(levelId.Trim()) != null)
            {
                issues.Add("错误：已有另一个 LevelDataAsset 使用了这个关卡 ID。");
            }

            return issues;
        }

        private LevelDataAsset FindExistingAssetByLevelId(string id)
        {
            if (!AssetDatabase.IsValidFolder(LevelsFolder))
            {
                return null;
            }

            var guids = AssetDatabase.FindAssets("t:LevelDataAsset", new[] { LevelsFolder });
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var asset = AssetDatabase.LoadAssetAtPath<LevelDataAsset>(path);
                if (asset != null && asset != loadedAsset && asset.levelId == id)
                {
                    return asset;
                }
            }

            return null;
        }

        private void ResizeGrid(int nextWidth, int nextHeight)
        {
            var nextTiles = new BaseTileType[nextWidth, nextHeight];
            for (var y = 0; y < nextHeight; y++)
            {
                for (var x = 0; x < nextWidth; x++)
                {
                    nextTiles[x, y] = x < width && y < height ? tiles[x, y] : BaseTileType.Floor;
                }
            }

            width = nextWidth;
            height = nextHeight;
            tiles = nextTiles;
            goals.RemoveWhere(goal => !IsInside(goal));
            boxes.RemoveWhere(box => !IsInside(box));
            if (hasPlayer && !IsInside(playerStart))
            {
                hasPlayer = false;
            }
        }

        private void EnsureGrid()
        {
            if (tiles == null || tiles.GetLength(0) != width || tiles.GetLength(1) != height)
            {
                CreateFilledGrid(BaseTileType.Floor);
            }
        }

        private void CreateFilledGrid(BaseTileType baseType)
        {
            tiles = new BaseTileType[width, height];
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    tiles[x, y] = baseType;
                }
            }

            boxes.RemoveWhere(box => !IsInside(box));
            goals.RemoveWhere(goal => !IsInside(goal));
            if (hasPlayer && !IsInside(playerStart))
            {
                hasPlayer = false;
            }
        }

        private static void EnsureLevelsFolder()
        {
            if (!AssetDatabase.IsValidFolder("Assets/PushBoxz"))
            {
                AssetDatabase.CreateFolder("Assets", "PushBoxz");
            }

            if (!AssetDatabase.IsValidFolder(LevelsFolder))
            {
                AssetDatabase.CreateFolder("Assets/PushBoxz", "Levels");
            }
        }

        private bool IsInside(Vector2Int position)
        {
            return position.x >= 0 && position.y >= 0 && position.x < width && position.y < height;
        }

        private bool IsWalkable(Vector2Int position)
        {
            return IsInside(position) && tiles[position.x, position.y] == BaseTileType.Floor;
        }

        private bool CanEditorPlayerOccupy(Vector2Int position)
        {
            return IsWalkable(position) && !boxes.Contains(position);
        }

        private Color GetTileColor(BaseTileType baseType)
        {
            switch (baseType)
            {
                case BaseTileType.Empty:
                    return emptyColor;
                case BaseTileType.Floor:
                    return floorColor;
                case BaseTileType.Wall:
                    return wallColor;
                default:
                    return Color.magenta;
            }
        }

        private string GetCellLabel(Vector2Int position)
        {
            if (hasPlayer && playerStart == position)
            {
                return "P" + GetDirectionLabel(editorPlayerFacing);
            }

            if (boxes.Contains(position))
            {
                return goals.Contains(position) ? "B*" : "B";
            }

            if (goals.Contains(position))
            {
                return "G";
            }

            return tiles[position.x, position.y] == BaseTileType.Wall ? "W" : string.Empty;
        }

        private static string GetDirectionLabel(Direction direction)
        {
            switch (direction)
            {
                case Direction.Up:
                    return "^";
                case Direction.Down:
                    return "v";
                case Direction.Left:
                    return "<";
                case Direction.Right:
                    return ">";
                default:
                    return string.Empty;
            }
        }

        private static Rect RectInset(Rect rect, float inset)
        {
            return new Rect(rect.x + inset, rect.y + inset, rect.width - inset * 2f, rect.height - inset * 2f);
        }

        private static string FormatPosition(Vector2Int position)
        {
            return "(" + position.x + ", " + position.y + ")";
        }

        private static string SanitizeFileName(string rawName)
        {
            var invalidCharacters = Path.GetInvalidFileNameChars();
            var cleanCharacters = rawName.Trim().Select(c => invalidCharacters.Contains(c) ? '_' : c).ToArray();
            var cleanName = new string(cleanCharacters);
            return string.IsNullOrWhiteSpace(cleanName) ? "LevelData" : cleanName;
        }

        private void SetMessage(string message, MessageType type)
        {
            lastMessage = message;
            lastMessageType = type;
        }

        private void SaveDraftState()
        {
            if (tiles == null)
            {
                return;
            }

            var draft = new DraftState
            {
                assetPath = loadedAsset != null ? AssetDatabase.GetAssetPath(loadedAsset) : string.Empty,
                levelId = levelId,
                width = width,
                height = height,
                playerX = playerStart.x,
                playerY = playerStart.y,
                hasPlayer = hasPlayer,
                playerFacing = (int)editorPlayerFacing,
                hasReverseDesignMode = true,
                reverseDesignMode = reverseDesignMode,
                activeBrush = (int)activeBrush
            };

            foreach (var box in boxes)
            {
                draft.boxes.Add(new BoxDraft
                {
                    x = box.x,
                    y = box.y
                });
            }

            foreach (var box in playbackStartBoxes)
            {
                draft.playbackStartBoxes.Add(new BoxDraft
                {
                    x = box.x,
                    y = box.y
                });
            }

            draft.playbackStartPlayerX = playbackStartPlayer.x;
            draft.playbackStartPlayerY = playbackStartPlayer.y;
            draft.solutionPlaybackIndex = solutionPlaybackIndex;

            for (var i = 0; i < generatedReverseActions.Count; i++)
            {
                var action = generatedReverseActions[i];
                draft.generatedActions.Add(new ActionDraft
                {
                    kind = (int)action.kind,
                    boxId = action.boxId,
                    direction = (int)action.direction,
                    playerFromX = action.playerFrom.x,
                    playerFromY = action.playerFrom.y,
                    playerToX = action.playerTo.x,
                    playerToY = action.playerTo.y,
                    boxFromX = action.boxFrom.x,
                    boxFromY = action.boxFrom.y,
                    boxToX = action.boxTo.x,
                    boxToY = action.boxTo.y
                });
            }

            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    draft.tiles.Add(new TileDraft
                    {
                        x = x,
                        y = y,
                        baseType = tiles[x, y],
                        hasGoal = goals.Contains(new Vector2Int(x, y))
                    });
                }
            }

            SessionState.SetString(DraftSessionKey, JsonUtility.ToJson(draft));
        }

        private bool RestoreDraftState()
        {
            var json = SessionState.GetString(DraftSessionKey, string.Empty);
            if (string.IsNullOrEmpty(json))
            {
                return false;
            }

            DraftState draft;
            try
            {
                draft = JsonUtility.FromJson<DraftState>(json);
            }
            catch (ArgumentException)
            {
                return false;
            }

            if (draft == null || draft.width < MinSize || draft.height < MinSize)
            {
                return false;
            }

            loadedAsset = string.IsNullOrEmpty(draft.assetPath)
                ? null
                : AssetDatabase.LoadAssetAtPath<LevelDataAsset>(draft.assetPath);
            levelId = string.IsNullOrEmpty(draft.levelId) ? "level_001" : draft.levelId;
            width = Mathf.Clamp(draft.width, MinSize, MaxSize);
            height = Mathf.Clamp(draft.height, MinSize, MaxSize);
            playerStart = new Vector2Int(draft.playerX, draft.playerY);
            hasPlayer = draft.hasPlayer;
            editorPlayerFacing = Enum.IsDefined(typeof(Direction), draft.playerFacing) ? (Direction)draft.playerFacing : Direction.Up;
            reverseDesignMode = !draft.hasReverseDesignMode || draft.reverseDesignMode;
            activeBrush = Enum.IsDefined(typeof(Brush), draft.activeBrush) ? (Brush)draft.activeBrush : Brush.Floor;

            goals.Clear();
            tiles = new BaseTileType[width, height];
            CreateFilledGrid(BaseTileType.Floor);

            if (draft.tiles != null)
            {
                foreach (var tile in draft.tiles)
                {
                    if (tile != null && tile.x >= 0 && tile.y >= 0 && tile.x < width && tile.y < height)
                    {
                        tiles[tile.x, tile.y] = tile.baseType;
                        if (tile.hasGoal)
                        {
                            goals.Add(new Vector2Int(tile.x, tile.y));
                        }
                    }
                }
            }

            boxes.Clear();
            if (draft.boxes != null)
            {
                foreach (var box in draft.boxes)
                {
                    if (box != null && box.x >= 0 && box.y >= 0 && box.x < width && box.y < height)
                    {
                        boxes.Add(new Vector2Int(box.x, box.y));
                    }
                }
            }

            if (hasPlayer && !IsInside(playerStart))
            {
                hasPlayer = false;
            }

            generatedReverseActions.Clear();
            if (draft.generatedActions != null)
            {
                foreach (var action in draft.generatedActions)
                {
                    if (action == null)
                    {
                        continue;
                    }

                    generatedReverseActions.Add(new AutoGeneratedAction
                    {
                        kind = Enum.IsDefined(typeof(AutoActionKind), action.kind) ? (AutoActionKind)action.kind : AutoActionKind.Move,
                        boxId = action.boxId,
                        direction = Enum.IsDefined(typeof(Direction), action.direction) ? (Direction)action.direction : Direction.Up,
                        playerFrom = new Vector2Int(action.playerFromX, action.playerFromY),
                        playerTo = new Vector2Int(action.playerToX, action.playerToY),
                        boxFrom = new Vector2Int(action.boxFromX, action.boxFromY),
                        boxTo = new Vector2Int(action.boxToX, action.boxToY)
                    });
                }
            }

            playbackStartPlayer = new Vector2Int(draft.playbackStartPlayerX, draft.playbackStartPlayerY);
            playbackStartBoxes.Clear();
            if (draft.playbackStartBoxes != null)
            {
                foreach (var box in draft.playbackStartBoxes)
                {
                    if (box != null)
                    {
                        playbackStartBoxes.Add(new Vector2Int(box.x, box.y));
                    }
                }
            }

            solutionPlaybackIndex = draft.solutionPlaybackIndex;

            return true;
        }
    }
}
